version: '3'
services:
  fancrowdapi:
    container_name: fan-crowd-api
    restart: always
    build: .
    ports:
      - '5000:5000'
    external_links:
      - mongo
    volumes: 
      - ./src:/usr/src/app/src
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - data:/data/db
 
volumes: 
 data: